### ISSUE TITLE
Python Getting Started Now Longer Works

### ISSUE THREAD

**Issue by darkn3rd** [grpc/grpc.io#1055]
## STEPS TO REPRODUCE

* https://grpc.io/docs/languages/python/quickstart/

## EXPECTED RESULTS

The steps in the getting started would work and the service would start.

## ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/home/user/getting-started/grpc/examples/python/helloworld/greeter_server.py", line 20, in <module>
    import helloworld_pb2
  File "/home/user/getting-started/grpc/examples/python/helloworld/helloworld_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/home/joaquin/.pyenv/versions/greeter-3.10.4/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by XuanWang-Amos** [comment]
Hi, have you tried regenerate code with protoc >= 3.19.0?
You can also try one of the two additional workarounds mentioned in the stack trace.
