### ISSUE TITLE
syntax error in package - re-created as previous closed with no solution

### ISSUE THREAD

**Issue by MrMajorThorburn** [grpc/grpc.io#22]
python -m pip install grpc --no-cache-dir
Collecting grpc
  Downloading https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\major\AppData\Local\Temp\pip-install-r9czerqi\grpc\setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "C:\Users\major\AppData\Local\Temp\pip-install-r9czerqi\grpc\grpc\__init__.py", line 6, in <module>
        from .rpc import *
      File "C:\Users\major\AppData\Local\Temp\pip-install-r9czerqi\grpc\grpc\rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\major\AppData\Local\Temp\pip-install-r9czerqi\grpc\

**Comment by nicolasnoble** [comment]
You are opening contextless issues on a repository that contains the source code of a website. Please stop doing that.
