### ISSUE TITLE
Website issue: python greeter_server.py Address already in use

### ISSUE THREAD

**Issue by scheung38** [grpc/grpc.io#738]
**Issue description**
Cannot launch server:

Traceback (most recent call last):
  File "$HOME/grpc/examples/python/helloworld/greeter_server.py", line 41, in <module>
    serve()
  File "$HOME/grpc/examples/python/helloworld/greeter_server.py", line 34, in serve
    server.add_insecure_port('[::]:50051')
  File "$HOME/grpc/examples/python/helloworld/.venv/lib/python3.9/site-packages/grpc/_server.py", line 961, in add_insecure_port
    return _common.validate_port_binding_result(
  File "$HOME/grpc/examples/python/helloworld/.venv/lib/python3.9/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address [::]:50051; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

Traceback (most recent call last):
  File "$HOME/grpc/examples/python/helloworld/greeter_client.py", line 37, in <module>
    run()
  File "$HOME/grpc/examples/python/helloworld/greeter_client.py", line 31, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "$HOME/grpc/examples/python/helloworld/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "$HOME/grpc/examples/python/helloworld/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1616634703.923922000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5397,"referenced_errors":[{"created":"@1616634703.923916000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"

**Steps to reproduce the issue**
python greeter_server.py  expect server to start

export GRPC_VERBOSITY=debug

**Expected behavior**
expect server to start

 
**Desktop (if relevant):**
 - OS: Mac OSX Big Sur
 - Browser CLI

python --version         
Python 3.9.1

**Comment by yashykt** [comment]
This is not the right page for questions or general gRPC help. Pleae re-direct questions to forums like the grpcio google group or stack-overflow.

While I'm here, I'll also note that from the logs it looks like the server is having trouble binding to the port. This mostly happens when the port is already in use. I would suggest using a different port.
